project:
  type: website
  output-dir: docs
  
website:
  title: "EDAV Fall 2023 Community Contribution"
  repo-url: https://github.com/YOUR_GITHUB_ACCOUNT/REPO_NAME
  repo-actions: [edit, issue]
  navbar:
    tools:
      - icon: github
        href: https://github.com/jtr13/edav2023
  sidebar:
    style: "floating"
    search: true
    contents:
      - welcome.qmd
      - project1.qmd
      - project2.qmd
      - project3.qmd
      - project7.qmd
      - project4.qmd
      - project5.qmd
      - project6.qmd
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023"
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    toc: true
    # code-fold: true

editor: source

